Yura rie プロコン競技問題集終了
kure-ict-club/competition-assignment pull request #3
Opened 2018-02-26 20:42 UTC by YuraRie

課題終わったので確認とmergeお願いします。
コンパイル、注意点、想定環境等はREADME.mdを参照願います。

2018-02-28 06:43 UTC, srpkdyy requested changes

2018-02-28 06:43 UTC, srpkdyy commented on YuraRie/Ex2/.gitignore
> +*.slo
.gitignoreはRootに1つでよさそうですね
.sln .vcxproj .vcxproj.filters の拡張子追加お願いします

2018-03-02 21:35 UTC, YuraRie commented on YuraRie/Ex2/.gitignore
> +*.slo
そうですね。環境で分けていましたが、統一したほうが少なくて済むのでそうします。

2018-03-02 21:46 UTC, YuraRie commented
mergeは自分で行う方がいいですか？

2018-03-03 01:36 UTC, srpkdyy commented
mergeは原則Github上かつ限られた人が行います
今回は @luling184 が行います

2018-03-03 01:42 UTC, srpkdyy commented on YuraRie/.gitignore
> +
拡張子の追加をお願いします
個人的情報が載る可能性のあるファイルはあげないようにしていきたいので

2018-03-03 16:51 UTC, YuraRie commented on YuraRie/.gitignore
> +
* 「.sln 」「.vcxproj 」「.vcxproj.filters」の3つのファイルはVSのソリューションのエントリポイントの定義ファイル等として環境再現に必須なので、.gitignoreへの追加は控えたほうがいいのでは？Makefifleの代わりみたいな扱いで考えています。
* ライブラリ等へのPATHは個人情報が乗る危険性がありますが、そのような定義は「*.vcxproj.user」ファイルとして分離し別方法で配布するのが通例です。(なおgitignoreに「*.user」は追加済み)

2018-03-04 01:54 UTC, srpkdyy commented on YuraRie/.gitignore
> +
了解です
コンフリクトが起きた場合、これらのファイルは解決できるのでしょうか？

2018-03-04 14:01 UTC, YuraRie commented on YuraRie/.gitignore
> +
可能です。
これらの定義ファイルは全てテキストファイル(xml)なので。

2018-03-05 07:32 UTC, srpkdyy commented on YuraRie/.gitignore
> +
了解です
@luling184 マージお願いします。

2018-03-05 07:32 UTC, srpkdyy approved these changes

2018-03-07 14:36 UTC, merged